// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace LinderaUnityBinding
{
    internal static unsafe partial class NativeMethodsGenerated
    {
#if UNITY_IOS && !UNITY_EDITOR
        const string __DllName = "__Internal";
#else
        const string __DllName = "lindera_ffi";
#endif
        





        /// <summary>
        ///  Create a new Lindera tokenizer with embedded IPADIC dictionary
        ///
        ///  # Returns
        ///  - Pointer to tokenizer handle on success
        ///  - NULL on failure
        /// </summary>
        [DllImport(__DllName, EntryPoint = "lindera_tokenizer_create", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern LinderaTokenizerHandle* lindera_tokenizer_create();

        /// <summary>
        ///  Destroy a tokenizer and free its resources
        ///
        ///  # Safety
        ///  - `handle` must be a valid pointer returned by `lindera_tokenizer_create`
        ///  - Must not be called twice on the same handle
        /// </summary>
        [DllImport(__DllName, EntryPoint = "lindera_tokenizer_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void lindera_tokenizer_destroy(LinderaTokenizerHandle* handle);

        /// <summary>
        ///  Tokenize UTF-8 text
        ///
        ///  # Arguments
        ///  - `handle`: Tokenizer handle
        ///  - `text`: UTF-8 encoded text (not null-terminated)
        ///  - `text_len`: Length of text in bytes
        ///
        ///  # Returns
        ///  - Pointer to token result on success
        ///  - NULL on failure
        ///
        ///  # Safety
        ///  - `handle` must be a valid tokenizer handle
        ///  - `text` must be a valid pointer to `text_len` bytes
        /// </summary>
        [DllImport(__DllName, EntryPoint = "lindera_tokenize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern LinderaTokenResultHandle* lindera_tokenize(LinderaTokenizerHandle* handle, byte* text, int text_len);

        /// <summary>
        ///  Get the number of tokens in a result
        ///
        ///  # Arguments
        ///  - `handle`: Token result handle
        ///
        ///  # Returns
        ///  - Number of tokens, or -1 on error
        /// </summary>
        [DllImport(__DllName, EntryPoint = "lindera_tokens_count", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int lindera_tokens_count(LinderaTokenResultHandle* handle);

        /// <summary>
        ///  Get a token at the specified index
        ///
        ///  # Arguments
        ///  - `handle`: Token result handle
        ///  - `index`: Token index
        ///
        ///  # Returns
        ///  - Pointer to token data, or NULL if out of bounds
        ///
        ///  # Note
        ///  The returned pointer is valid until `lindera_tokens_destroy` is called
        /// </summary>
        [DllImport(__DllName, EntryPoint = "lindera_tokens_get", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern TokenData* lindera_tokens_get(LinderaTokenResultHandle* handle, int index);

        /// <summary>
        ///  Destroy token result and free all associated memory
        ///
        ///  # Safety
        ///  - `handle` must be a valid pointer returned by `lindera_tokenize`
        ///  - Must not be called twice on the same handle
        /// </summary>
        [DllImport(__DllName, EntryPoint = "lindera_tokens_destroy", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void lindera_tokens_destroy(LinderaTokenResultHandle* handle);

        /// <summary>
        ///  Free a string allocated by this library
        ///
        ///  # Safety
        ///  - `str` must be a valid pointer returned by this library
        /// </summary>
        [DllImport(__DllName, EntryPoint = "lindera_string_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void lindera_string_free(byte* str);


    }

    /// <summary>
    ///  Opaque handle to the Lindera tokenizer (FFI)
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct LinderaTokenizerHandle
    {
    }

    /// <summary>
    ///  Result of tokenization containing tokens (FFI)
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct LinderaTokenResultHandle
    {
    }

    /// <summary>
    ///  FFI-safe token data structure
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TokenData
    {
        /// <summary>
        ///  Token surface text (null-terminated UTF-8)
        /// </summary>
        public byte* text;
        /// <summary>
        ///  Byte start position
        /// </summary>
        public uint byte_start;
        /// <summary>
        ///  Byte end position
        /// </summary>
        public uint byte_end;
        /// <summary>
        ///  Token position index
        /// </summary>
        public uint position;
        /// <summary>
        ///  Token details (null-terminated UTF-8, comma-separated)
        /// </summary>
        public byte* details;
    }



}
